[build]
  command = "cd server && npm install && npm start"
  publish = "client/dist"  # Carpeta de salida de tu frontend (React/Vite)
  functions = "server"      # Carpeta con el backend

[[redirects]]
  from = "/cv"
  to = "/.netlify/functions/server/public/CV.pdf"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/server/contact"
  status = 200
